language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: RYrQgEI9FKcxxdVW64pOpnymGukT5QUen9QQAM2DGQA0UWCv5YDub0y3J9rBUjhsIceiJB2c4cfMOTC//ktark2FXaA9pXP9S7KdrCZWVrmJ1hlgEcBHo6hre7OKDOi96Q5BU+ifIth/6kW3gvb0aydjdRdHkXKDUPT+gw0yE1O1LCg0GO0+dNqSuxcuYdDoTJFTGrm9JmBfsq204GdszzZcdMbmJUyWmZa8dmrwGG2gGCscjAHSMTUQR05433GIae1ya6E2s7oe1aKBU4XE3HyMyrmUFK95HIQCT4qZyq4LRi3SlolDV1UO0i2z5PvG1c7PSYE6vwXVEDwkSUHkHc8plzsFucL8TZ6SMDFb4iKBjKInkY2nfiwQHn2shKNbsaQrhe56zAHOExKh0o+HQRIiNx61916FAxHJjUSzeHCWUmY2GWdm+doU2WchY7U7W5pR+kI16r6ijp5iGdk2VnUFb3oKm7fLv/6Y+AcgnucKXdsCU3OdYoRRvmroM+CB461kd0H2+linzNLxMtkumyZEAs/2bLeOTGKANGz4YP/jsW8qNOhGRlyzJxA7rpnzaBOa4bvZymoR2irUkEX74vzzotRcweLrHDH32EYUh0AzcccwCIKw/W8rmEsCZkhCkDnX/k0jcJhp65K+RRiAQud+PFgtugo0oBu8aYNra/w=
  app: tt-trip-tracker
